version: '3.8'

services:
  frontend:
    image: techdemo-frontend:latest
    container_name: techdemo-frontend
    ports:
      - "3000:3000"

  backend:
    image: techdemo-backend:latest
    container_name: techdemo-backend
    ports:
      - "8080:8080"

  techdemo-mongodb:
    image: mongo
    container_name: techdemo-mongodb
    ports:
      - "27017:27017"
    env_file:
      - .env
    volumes:
      - mongodb_data:/data/db
    networks:
      - techdemo-network

networks:
  techdemo-network:
    driver: bridge

volumes:
  mongodb_data:
